import { Project } from "@/types/projects";
import { JournalEntry } from "@/types/journal";
import { ChatMessage } from "@/types/chat";
import { AgentId } from "@/types/agents";

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 60);
}

export function projectFilename(project: Project): string {
  return `${slugify(project.name)}-${project.id.slice(-6)}.md`;
}

export function renderProjectMarkdown(project: Project): string {
  const frontmatter = [
    "---",
    `type: project`,
    `status: ${project.status}`,
    `created: ${project.createdAt}`,
    `updated: ${project.updatedAt}`,
    `tags: [agentctrl, project]`,
    "---",
    "",
  ].join("\n");

  const lines: string[] = [`# ${project.name}`, ""];
  if (project.goal) lines.push(`**Goal:** ${project.goal}`, "");
  if (project.description) lines.push(project.description, "");

  const done = project.tasks.filter((t) => t.status === "done").length;
  lines.push(`## Tasks (${done}/${project.tasks.length})`, "");

  if (project.tasks.length === 0) {
    lines.push("_No tasks yet._");
  } else {
    for (const task of project.tasks) {
      const checked = task.status === "done" ? "x" : " ";
      const agents = task.assignedAgentIds.length ? ` — [[${task.assignedAgentIds.join("]], [[")}]]` : "";
      lines.push(`- [${checked}] ${task.title} \`${task.status}\`${agents}`);
    }
  }

  return frontmatter + lines.join("\n") + "\n";
}

export function journalFilename(entry: JournalEntry): string {
  return `${entry.date}.md`;
}

export function renderJournalMarkdown(entry: JournalEntry): string {
  const frontmatter = [
    "---",
    `type: journal`,
    `agent: ${entry.agentId}`,
    `date: ${entry.date}`,
    `tags: [agentctrl, journal, ${entry.agentId}]`,
    "---",
    "",
  ].join("\n");

  return `${frontmatter}# ${capitalize(entry.agentId)} — ${entry.date}\n\n${entry.content}\n`;
}

export function renderChatMarkdown(agentId: AgentId, messages: ChatMessage[]): string {
  const frontmatter = ["---", `type: chat`, `agent: ${agentId}`, `tags: [agentctrl, chat, ${agentId}]`, "---", ""].join("\n");

  const lines: string[] = [`# Chat with ${capitalize(agentId)}`, ""];
  for (const m of messages) {
    const time = new Date(m.createdAt).toISOString().slice(11, 16);
    const speaker = m.role === "user" ? "You" : capitalize(agentId);
    const link = m.taskId ? ` _(→ task created)_` : "";
    lines.push(`**[${time}] ${speaker}:** ${m.content}${link}`, "");
  }

  return frontmatter + lines.join("\n");
}

/**
 * Deliberately excludes any wall-clock "last synced" timestamp — this file
 * is committed on every sync, so any value that changes on every call
 * (like `new Date()`) would defeat the git-diff-based no-op detection in
 * lib/vault/sync.ts and cause a spurious commit+push every 10 minutes even
 * when nothing actually changed. Sync status/timing lives in
 * /api/vault/status instead (in-memory, not committed).
 */
export function vaultReadme(counts: { projects: number; journalEntries: number; chatThreads: number }): string {
  return [
    "# AgentCtrl Vault",
    "",
    "Auto-generated by AgentCtrl's Obsidian sync — regenerated on every sync, do not edit these files directly (edits will be overwritten).",
    "",
    `- ${counts.projects} project(s) in \`Projects/\``,
    `- ${counts.journalEntries} journal entrie(s) in \`Journal/<agent>/\``,
    `- ${counts.chatThreads} chat thread(s) in \`Chat/\``,
    "",
  ].join("\n");
}

function capitalize(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
